import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Sidebar from "@/layouts/sidebar/Sidebar";
import Header from "@/layouts/header/Header";
import Footer from "@/layouts/footer/Footer";
import ProtectedRoute from "@/core/auth/ProtectedRoute";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gestion de factures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Sidebar />
        <div className="main-container">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
